const carList = [
  {
    image: "https://shorturl.at/ipx35",
    brand: "Toyota",
    model: "Corolla",
    year: 2018,
    power: "140 HP",
    mileage: "50,000 km",
    price: "$20,000",
  },
  {
    image: "https://shorturl.at/vJX08",
    brand: "Volkswagen",
    model: "Golf",
    year: 2019,
    power: "120 HP",
    mileage: "40,000 km",
    price: "$22,000",
  },
  {
    image: "https://shorturl.at/zJLOY",
    brand: "Ford",
    model: "Focus",
    year: 2017,
    power: "130 HP",
    mileage: "60,000 km",
    price: "$18,000",
  },
  {
    image: "https://example.com/honda_civic.jpg",
    brand: "Honda",
    model: "Civic",
    year: 2015,
    power: "125 HP",
    mileage: "70,000 km",
    price: "$15,500",
  },
  {
    image: "https://example.com/bmw_3series.jpg",
    brand: "BMW",
    model: "3 Series",
    year: 2016,
    power: "160 HP",
    mileage: "45,000 km",
    price: "$25,000",
  },
  {
    image: "https://example.com/audi_a4.jpg",
    brand: "Audi",
    model: "A4",
    year: 2014,
    power: "150 HP",
    mileage: "55,000 km",
    price: "$21,000",
  },
  {
    image: "https://example.com/mercedes_c_class.jpg",
    brand: "Mercedes-Benz",
    model: "C-Class",
    year: 2017,
    power: "180 HP",
    mileage: "55,000 km",
    price: "$28,000",
  },
  {
    image: "https://example.com/bmw_x5.jpg",
    brand: "BMW",
    model: "X5",
    year: 2019,
    power: "250 HP",
    mileage: "30,000 km",
    price: "$45,000",
  },
  {
    image: "https://example.com/audi_q7.jpg",
    brand: "Audi",
    model: "Q7",
    year: 2018,
    power: "200 HP",
    mileage: "40,000 km",
    price: "$38,000",
  },
  {
    image: "https://example.com/ford_mustang.jpg",
    brand: "Ford",
    model: "Mustang",
    year: 2016,
    power: "300 HP",
    mileage: "25,000 km",
    price: "$32,000",
  },
  {
    image: "https://example.com/toyota_camry.jpg",
    brand: "Toyota",
    model: "Camry",
    year: 2020,
    power: "190 HP",
    mileage: "20,000 km",
    price: "$26,500",
  },
  {
    image: "https://example.com/hyundai_santa_fe.jpg",
    brand: "Hyundai",
    model: "Santa Fe",
    year: 2019,
    power: "170 HP",
    mileage: "35,000 km",
    price: "$24,000",
  },
  {
    image: "https://example.com/lancia_delta_integrale.jpg",
    brand: "Lancia",
    model: "Delta Integrale",
    year: 1992,
    power: "200 HP",
    mileage: "80,000 km",
    price: "$20,000",
  },
  {
    image: "https://example.com/renault_avantime.jpg",
    brand: "Renault",
    model: "Avantime",
    year: 2002,
    power: "165 HP",
    mileage: "100,000 km",
    price: "$12,500",
  },
  {
    image: "https://example.com/peugeot_205_gti.jpg",
    brand: "Peugeot",
    model: "205 GTI",
    year: 1991,
    power: "130 HP",
    mileage: "70,000 km",
    price: "$15,000",
  },
  {
    image: "https://example.com/datsun_240z.jpg",
    brand: "Datsun",
    model: "240Z",
    year: 1970,
    power: "150 HP",
    mileage: "50,000 km",
    price: "$40,000",
  },
  {
    image: "https://example.com/isuzu_vehicross.jpg",
    brand: "Isuzu",
    model: "Vehicross",
    year: 1999,
    power: "215 HP",
    mileage: "90,000 km",
    price: "$8,000",
  },
  {
    image: "https://example.com/dacia_1300.jpg",
    brand: "Dacia",
    model: "1300",
    year: 1990,
    power: "70 HP",
    mileage: "120,000 km",
    price: "$3,500",
  },
  {
    image: "https://example.com/saab_900_turbo.jpg",
    brand: "Saab",
    model: "900 Turbo",
    year: 1993,
    power: "185 HP",
    mileage: "85,000 km",
    price: "$9,500",
  },
  {
    image: "https://example.com/plymouth_prowler.jpg",
    brand: "Plymouth",
    model: "Prowler",
    year: 1999,
    power: "253 HP",
    mileage: "70,000 km",
    price: "$20,000",
  },
  {
    image: "https://example.com/alfa_romeo_sz.jpg",
    brand: "Alfa Romeo",
    model: "SZ",
    year: 1991,
    power: "210 HP",
    mileage: "60,000 km",
    price: "$25,000",
  },
  {
    image: "https://example.com/mitsubishi_3000gt.jpg",
    brand: "Mitsubishi",
    model: "3000GT",
    year: 1995,
    power: "300 HP",
    mileage: "80,000 km",
    price: "$12,000",
  },
  {
    image: "https://example.com/lotus_elise.jpg",
    brand: "Lotus",
    model: "Elise",
    year: 2000,
    power: "190 HP",
    mileage: "50,000 km",
    price: "$30,000",
  },
  {
    image: "https://example.com/subaru_sv_x.jpg",
    brand: "Subaru",
    model: "SVX",
    year: 1992,
    power: "230 HP",
    mileage: "90,000 km",
    price: "$7,500",
  },
];

console.log(carList.length);
